# Generated by Django 3.2.8 on 2022-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=15)),
                ('proid', models.IntegerField()),
                ('procategory', models.CharField(max_length=20)),
                ('proprice', models.FloatField()),
                ('proimage', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
