# Generated by Django 3.2.8 on 2022-05-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proimage',
            field=models.ImageField(upload_to='shop1/images'),
        ),
    ]
